# very simple, general makefile thingamajig i have going on but i know little about what actually is happening right now (what is a c library?!?!?!)
all:
	gcc main.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
